# Generated by Django 3.2.4 on 2021-06-26 23:52

import data.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0002_auto_20210625_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetLinkedAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PetProfile',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='data.animalmodel')),
                ('description', models.CharField(max_length=512)),
                ('profile_image', models.ImageField(upload_to=data.models.get_upload_path)),
            ],
        ),
        migrations.RenameField(
            model_name='behaviormodel',
            old_name='date',
            new_name='modified',
        ),
        migrations.AddField(
            model_name='animalmodel',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='animalmodel',
            name='owner',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animalmodel',
            name='animal_name',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterUniqueTogether(
            name='animalmodel',
            unique_together={('owner', 'animal_type', 'animal_name')},
        ),
        migrations.CreateModel(
            name='PetPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=512)),
                ('attachment', models.ImageField(upload_to=data.models.get_upload_path)),
                ('created', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.petprofile')),
            ],
        ),
    ]
