# Generated by Django 3.2.4 on 2021-06-26 23:58

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20210626_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petprofile',
            name='description',
        ),
        migrations.AddField(
            model_name='petprofile',
            name='profile_description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='petpost',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to=data.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=data.models.get_upload_path),
        ),
    ]
