# Generated by Django 3.2.4 on 2021-06-28 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='petlinkedaccount',
            name='account_type',
            field=models.CharField(choices=[('Instagram', 'Instagram'), ('Twitter', 'Twitter'), ('Facebook', 'Facebook')], default='Instagram', editable=False, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petlinkedaccount',
            name='account_url',
            field=models.URLField(default='/', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petlinkedaccount',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
