# Generated by Django 3.2.4 on 2021-06-29 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20210627_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalmodel',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animalmodel',
            name='age_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
