# Generated by Django 3.2.4 on 2021-06-29 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20210628_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalmodel',
            name='animal_breed',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
