# Generated by Django 3.2.4 on 2021-07-03 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('data', '0009_animalmodel_animal_breed'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('theme', models.CharField(choices=[('Light', 'Light'), ('Dark', 'Dark')], max_length=50)),
                ('default_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.petprofile')),
            ],
        ),
    ]
