# Generated by Django 3.2.4 on 2021-07-16 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_userpreferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petpost',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_set', to='data.petprofile'),
        ),
    ]
